spring:
  application:
    name: api-admin-server
  profiles:
    default: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc://mariadb


server:
  port: 8080

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

